# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.BinaryField(),
        ),
    ]
