# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20161201_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
