# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='easy_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='size_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_width',
            field=models.FloatField(default=0),
        ),
    ]
